### ISSUE TITLE
mongo-connector memory consumption keeps on increasing till it is killed for server limit

### ISSUE THREAD

**Issue by sprypradeep** [yougov/mongo-connector#122]
This happens at starting a fresh connector. It dies before it can complete a dump of collection. collection dump does not do batch uploads for better scalability. I'm using the auto-commit-interval as well to make sure it keeps dumping data to solr and does not mount up. my collection has a million records. Either it should have a default dump size or provide a config option for such. earlier version of connector work fine as that does not mount the whole collection in memory before dumping.

**Comment by prashant2101** [comment]
Hi @llvtt ,

I am using mongo-connnector to sync MongoDB and Elasticsearch. Can you please explain why the documents indexing gets stuck after some time. My Mongo collection has ~24k docs, out of which after ~8k documents get indexed, the process gets stuck. The performance is same with and without --no-dump.
