### ISSUE TITLE
Specifying which fields ElasticSearch should index

### ISSUE THREAD

**Issue by byronm** [yougov/mongo-connector#150]
I'm using the ElasticSearch `DocManager` to index our database for full text search. I see that MongoConnector will automatically copy all data into Elastic upon first run, and subsequently sync by applying the oplog. However, I'd like control over exactly what gets synced to Elastic: certain fields are irrelevant to search, for example, and I don't want to duplicate the data.

I found the `--fields` flag, but unless I'm misunderstanding the arg, it seems like it's just a top level whitelisting of the fields to sync across all the collections. Is it possible to whitelist fields on a per-collection basis? Is it also possible to specify this in a configuration file, akin to the Solr version's `schema.xml`, instead of dumping it all on the command line?

Beyond just fields, is it possible to specify which collections you want to sync? There are some that I don't need to store in Elastic at all. (It wouldn't be a big deal to just delete the index in Elastic after the initial sync, but I suspect it would keep getting recreated as insertions are made in mongo).

Thanks for any guidance you can provide!

**Comment by Apoorva333** [comment]
Any update on filtering documents based on value using mongo-connector?
