### ISSUE TITLE
Dates do not contain timezone

### ISSUE THREAD

**Issue by heichwald** [yougov/mongo-connector#184]
Hello,

I am pushing content to elastic search but the dates do not have the timezone.
In Mongo I have a field "publishDate" : ISODate("2013-12-23T19:45:00.000Z")
but when I print the doc in the bulk function;
 @wrap_exceptions
    def bulk_upsert(self, docs):

I see : u'publishedDate': datetime.datetime(2013, 12, 23, 19, 45)
and this gets pushed to elastic as "2013-12-23T19:45:00" which is not UTC anymore but local date according to ISO8601

Is there a bug somewhere? maybe using BSON.bsondecode(as_class=<type 'dict'>, tz_aware=False) ?

Thanks

**Comment by Sekhar-jami** [comment]
@llvtt 
I have tried using --tz-aware option but the connector, still seems to be changing the date format:

I have a date field as follows:
"postedDate" : ISODate("2013-12-23T00:00:00.000+0000"), 
but when I check the logs, mongo-connector is converting it to "2013-12-23T00:00:00+00:00". Is there a way to retain the exactly same value?
