### ISSUE TITLE
How can we make sure data is in sync in source and target using mongo-connector? I mean validate the data in source and target 

### ISSUE THREAD

**Issue by vreddy2154** [yougov/mongo-connector#844]

**Comment by vreddy2154** [comment]
We are using mongo-connector to sync few collections from Mongo 3.2 to Mongo 4.0,one of the things we are looking for is how can we make sure data is same in source and target ? Is there a way we can validate the data?

**Comment by jaraco** [comment]
Perhaps [the answers here would help](https://stackoverflow.com/questions/41222805/compare-a-mongo-diff-on-two-collections). As far as I know, there's nothing mongo-connector can do to help.

**Comment by vreddy2154** [comment]
Can you have mongo-connector ability to compare the data and make sure its in Sync.If we are using mongo-connector to sync data from cluster to another we need to make sure data is also in sync as users will be pulling real time reports .
