### ISSUE TITLE
Seeking help in connecting mongodb-atlas to elasticsearch cloud

### ISSUE THREAD

**Issue by ooihuiying** [yougov/mongo-connector#903]
Hi, i have several questions which i hope anyone can help.

1) Does the command below need to be run repeatedly or just once to establish the connection between mongodb atlas and elasticsearch cloud? 
`
mongo-connector -m mongodb+srv://userName:Password@cluster0.t21ms.mongodb.net/DB?retryWrites=true&w=majority -t https://c80872f3180d47059f918e05a3b33555.ap-southeast-1.aws.found.io:9243/ -d elastic2_doc_manager`

2) Connecting to Elasticsearch requires a password and username, from what i understand an alternative command to the above is: **mongo-connector -c config.json** where i can specify a JSON file to load configurations from and input my password and username.

However, when i do so i face the problem where the commands doesnt execute. It seems as though it has hung and nothing is happening. It stops printing any log halfway through...

![image](https://user-images.githubusercontent.com/40648338/89657073-180d3400-d8ff-11ea-8d77-42e8a7b145c4.png)

Can i check if my config file is correct? This issue only happens when i add the namespaces field. My database on mongodb atlas has 2 collections but i only want to push one of the collection into elasticsearch, hence i added this.

```
{
    "mainAddress": "mongodb+srv://userName:Password@cluster0.t21ms.mongodb.net/DB?retryWrites=true&w=majority",
    "verbosity": 1,
    "ssl": {
        "sslCertificatePolicy": "required"
    },
    "namespaces": {
        "include": [
            "DATABASENAME.COLLECTIONNAME"
        ]
    },
    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": "https://c80872f3180d47059f918e05a3b33555.ap-southeast-1.aws.found.io:9243/ -d elastic2_doc_manager",
            "args": {
                "clientOptions": {
                    "http_auth": [
                        "USERNAME",
                        "PASSWORD"
                    ],
                    "use_ssl": true
                }
            }
        }
    ]
}
```

3)  When i make a GET request to view if data has been stored in elasticsearch, it seems nothing was pushed to elasticsearch.
```
{
"took": 1,
"timed_out": false,
"_shards": {
"total": 3,
"successful": 3,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 0,
"relation": "eq"
},
"max_score": null,
"hits": []
}
}
```

**Comment by EvaOyy** [comment]
i have the same problem too!

**Comment by veerandra7** [comment]
Got any solution for this ? I am getting same problem
