### ISSUE TITLE
Solr arrays not getting inserted in to solr

### ISSUE THREAD

**Issue by acmeinternetsolutions** [yougov/mongo-connector#99]
Hi I'm running mongo-connector latest build and I'm unable to insert list values into solr multiValued fields.  In my test index, I have the followling solr fields.

```
<field name="_id" type="string" indexed="true" stored="true" required="true" multiValued="false" />
   <field name="_ts" type="long" indexed="true" stored="true" multiValued="false" />
   <field name="_ns" type="string" indexed="true" stored="true" multiValued="false" />
   <field name="spec_name" type = "string" indexed = "true" stored = "true" multiValued="true"/>
   <field name="spec_value" type = "string" indexed = "true" stored = "true" multiValued="true"/>
```

Given these two documents from my mongodb 

```
{ "_id" : ObjectId("5320d76ebdca98e379b97b9b"), "jobID" : "2597402", "spec_value" : "20" }
{ "_id" : ObjectId("5320d7ccbdca98e379b97b9c"), "jobID" : "2597402", "spec_name" : [  "one",  "two" ], "spec_value" : [  "20",  "test" ] }
```

the first document inserts the spec_value field correctly, but the second does not.  

Is this possibly a bug?

Also, here is my mongo-connector call for starting it up.

```
mongo-connector -m localhost:27017 -t http://localhost:8181/solr/content  -d mongo-connector/mongo_connector/doc_managers/solr_doc_manager.py -n test.test -a tomcat -p tomcat -i spec_name,spec_value,jobID
```

Thanks for any help you may offer,
Tim

**Comment by zakpatterson** [comment]
Following this issue, I also have a problem inserting into arrays, however my structure is a little different.  I have in mongo: 

    { 
       locations : [
         ..., { name : "chicago, il", contact : {name : "curious george", email : "georgesemail"}},
      ..]
    } 

And I want to pull out all names.  locations*.contact.name is not allowed unfortunately by dynamicField.  

Is there any way to get at this?

**Comment by pksoman** [comment]
I see this post is closed. However, I would like to know if there is any way to handle an array of String within an array of Object.

Ex:

{
  "name":  "doc1",
   "a" : [
                 {
                            "b" : "something.0",
                            "c" : [
                                        "1001",
                                         "1002"
                                    ]
                },{
                            "b" : "something.1",
                            "c" : [
                                        "1006",
                                         "1007"
                                    ]
                }
     ]
},
{
  "name":  "doc2",
   "a" : [
                 {
                            "b" : "something.2",
                            "c" : [
                                        "1001",
                                         "1002"
                                    ]
                },{
                            "b" : "something 3",
                            "c" : [
                                        "1006",
                                         "1007"
                                    ]
                }
     ]
}

This get converted as 
{
"name" : "doc1",
a.0.b = "something.0",
a.0.c.0 = "1001",
a.0.c.1 = "1002"
a.1.b="something.1",
a.1.c.0 = "1006",
a.1.c.1 = "1007"
},
{
"name" : "doc2",
a.0.b = "something.2",
a.0.c.0 = "1001",
a.0.c.1 = "1002",
a.1.b="something.3",
a.1.c.0 = "1006",
a.1.c.1 = "1007"
}

Now how can I search in Solr to match all documents that has 
a.*.b="something.0" and a.*.c contains "1002"

Sorry for the lengthy detail.
